version: '3.1'

services:
  db:
    build: .
    container_name: postgre_movies
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: movies