CREATE EXTENSION pgcrypto;

CREATE TABLE user_account
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skey          varchar(32) UNIQUE NOT NULL,
    username      text UNIQUE        NOT NULL,
    firstname     text,
    lastname      text,
    password_hash varchar(255),
    salt          varchar(16),
    country       text,
    time_added    timestamptz        NOT NULL
);

